---
apiVersion: v1
kind: ConfigMap
metadata:
  name: descheduler-policy-configmap
  namespace: kube-system
data:
  policy.yaml: |
    apiVersion: "descheduler/v1alpha2"
    kind: "DeschedulerPolicy"
    profiles:
      - name: ProfileName
        pluginConfig:
        - name: "PodLifeTime"
          args:
            maxPodLifeTimeSeconds: 86400 # 24 hours
            namespaces:
              include:
              - "infra"
            labelSelector:
              matchLabels:
                team: cloudops
          matchExpressions:
        plugins:
          deschedule:
            enabled:
              - "PodLifeTime"
